---
- name: Install/update python dependencies
  pip: name={{ item }} state=present executable=pip3 extra_args=--upgrade
  with_items:
    - pip
    - requests
    - SpeechRecognition
    - setuptools
    - wheel
    - pocketsphinx
    - cherrypy
    - pyalsaaudio
    - webrtcvad
    - pyyaml
    - coloredlogs
    - future
    - pexpect
    - pythonvlc
    - tenacity

- name: Clean application path
  file:
    path: "{{ app_path }}"
    state: absent

- name: Clone the Another Smart Mirror app
  git:
    repo: git@github.com:jreyes/asm-app.git
    dest: "{{ app_path }}"
    accept_hostkey: yes
    force: yes
    recursive: no
    key_file: "/home/jreyes/.ssh/id_rsa.github"

- name: Build the Another Smart Mirror app
  command: chdir={{ app_path }} npm install

- name: Copy screenly systemd units
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
    - X.service
    - matchbox.service
    - asm-electron.service

- name: Set the correct user/group to directory
  file:
    path: "/home/{{ app_user }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0775
    state: directory
    recurse: yes
