---
- name: Install/update python dependencies
  pip: name={{ item }} state=present executable=pip3
  with_items:
    - requests
    - pyaudio
    - SpeechRecognition

- name: Clean artifacts
  file:
    state: absent
    path: "{{ artifact_path }}/"
  with_items:
    - {{ app_path }}
    - {{ electron_path }}

- name: Clone the Another Smart Mirror app
  git:
    repo: git@github.com:jreyes/asm-app.git
    dest: "{{ app_path }}"
    accept_hostkey: yes
    force: yes
    recursive: no
    key_file: "/home/{{ app_user }}/.ssh/id_rsa.github"

- name: Build the Another Smart Mirror app
  command: chdir={{ app_path }} yarn install

- name: Copy screenly systemd units
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
    - X.service
    - matchbox.service
    - asm-electron.service
  become: true
