---
- name: Generate encrypted password
  shell: mkpasswd --method=SHA-512 {{ app_user_password }}
  register: encrypted_user_password

- name: MirrorApp group creation
  group:
    name: "{{ app_user }}"
    state: present

- name: Create MirrorApp user account
  user:
    name: "{{ app_user }}"
    group: "{{ app_user }}"
    groups: sudo
    password: "{{ encrypted_user_password.stdout }}"
    state: present
    append: yes
    shell: "/bin/bash"
    createhome: "yes"
    update_password: always
