---
- name: Generate encrypted password
  shell: mkpasswd --method=SHA-512 {{ app_user_password }}
  register: encrypted_user_password

- name: Create "mirror" user/group
  user:
    name: "{{ app_user }}"
    password: "{{ encrypted_user_password.stdout }}"
    state: present
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: "/home/{{ app_user }}/.ssh/id_rsa"
    append: yes
    shell: "/bin/bash"
    update_password: always

- name: Ensures autologin dir exists
  file:
    path: "/etc/systemd/system/getty@tty1.service.d"
    state: directory

- name: Setup the autologin
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/getty@tty1.service.d/{{ item }}"
  with_items:
    - override.conf
