---
- hosts: all
  gather_facts: yes

  vars:
    app_user: "{{ ansible_user }}"
    app_path: "/home/{{ ansible_user }}/asm-app"
    electron_path: "/home/{{ ansible_user }}/.electron"
    lightdm_autologin_user: "{{ ansible_user }}"
    nodejs_version: "7.x"

  roles:
    - system
    - geerlingguy.nodejs
    - application
    - splashscreen
    - gantsign.lightdm
