---
- hosts: all
  gather_facts: yes

  vars:
    app_user: "{{ ansible_user }}"
    app_path: "/home/{{ ansible_user }}/asm-app"
    electron_path: "/home/{{ ansible_user }}/.electron"
    nodejs_version: "7.x"

  roles:
    - system
    - geerlingguy.nodejs
    - fubarhouse.yarn
    - application
    - splashscreen
