---
- hosts: all
  gather_facts: yes

  vars:
    app_user: "mirror"
    app_path: "/home/mirror/asm-app"
    lightdm_autologin_user: "mirror"
    nodejs_version: "7.x"

  vars_prompt:
    - name: "app_user_password"
      prompt: "Enter a password for the user"
      private: yes
      confirm: yes

  roles:
    - system
    - user
    - role: geerlingguy.nodejs
      sudo: yes
    - application
    - splashscreen
    - gantsign.lightdm
