---
- hosts: all
  gather_facts: yes

  vars:
    app_user: "mirror"
    app_path: "/home/mirror/asm-app"
    lightdm_autologin_user: "mirror"
    nodejs_version: "7.x"

  roles:
    - system
    - role: geerlingguy.nodejs
      sudo: yes
    - application
    - splashscreen
    - gantsign.lightdm
