---
- name: Create splashscreen directories
  file:
    path: "{{ item }}"
    recurse: yes
    state: directory
  with_items:
    - /usr/share/plymouth/themes/AnotherSmartMirror
    - /etc/plymouth
  become: true

- name: Copy splashscreen theme
  copy:
    src: "{{ item }}"
    dest: "/usr/share/plymouth/themes/AnotherSmartMirror/{{ item }}"
    force: no
  with_items:
    - AnotherSmartMirror.png
    - AnotherSmartMirror.script
    - AnotherSmartMirror.plymouth
  become: true

- name: Update Plymouth
  copy:
    src: 'AnotherSmartMirror.conf'
    dest: '/etc/plymouth/plymouthd.conf'
  become: true
  notify: [ 'Update initramfs' ]