---
- name: Copy splashscreen theme
  copy:
    src: "{{ item }}"
    dest: "/usr/share/plymouth/themes/AnotherSmartMirror/{{ item }}"
    force: no
  with_items:
    - AnotherSmartMirror.jpg
    - AnotherSmartMirror.script
    - AnotherSmartMirror.plymouth

- name: Enables splashscreen
  command: plymouth-set-default-theme -R AnotherSmartMirror
